// Package declaration — this class belongs to the 'model' layer and represents a database entity
package com.items.model;

/**
 * Represents an inventory item record from the ITEMS database table.
 * Each item has a unique ID, a name, a price, and a stock quantity (totalNumber).
 * This POJO (Plain Old Java Object) is used across all layers:
 *   - Controller: receives form data and sends items to the view
 *   - Service:   passes items between controller and DAO
 *   - View (JSP): displays item properties on the page
 *
 * Database columns: ID (PK, NUMBER), NAME (VARCHAR2), PRICE (NUMBER), TOTAL_NUMBER (NUMBER)
 */
public class Item {

    // Unique identifier for each item — auto-generated by the database sequence
    private long id;
    // Display name of the item (e.g., "Wireless Mouse")
    private String name;
    // Selling price of the item in dollars (supports decimals, e.g., 29.99)
    private double price;
    // Current stock quantity — how many units are available
    private int totalNumber;

    /**
     * Default no-argument constructor.
     * Required by the Servlet spec for JSP useBean and by some frameworks
     * that create objects via reflection before calling setters.
     */
    public Item() {}

    /**
     * Constructor WITHOUT an ID — used when preparing to INSERT a brand-new item.
     * The database will assign the ID automatically (via a sequence + trigger).
     *
     * @param name        the item's display name
     * @param price       the unit price
     * @param totalNumber the quantity in stock
     */
    public Item(String name, double price, int totalNumber) {
        this.name = name;
        this.price = price;
        this.totalNumber = totalNumber;
    }

    /**
     * Constructor WITH an ID — used when updating an existing item or reading one from the DB.
     * The ID is already known because it comes from an existing database record.
     *
     * @param id          the existing item's primary key
     * @param name        the item's display name
     * @param price       the unit price
     * @param totalNumber the quantity in stock
     */
    public Item(long id, String name, double price, int totalNumber) {
        this.id = id;
        this.name = name;
        this.price = price;
        this.totalNumber = totalNumber;
    }

    // --- Getters and setters ---
    // Getters retrieve field values (used by JSP EL and Java code).
    // Setters mutate field values (used when populating from a ResultSet or form).
    // Note: setId accepts 'int' but stores as 'long' — this works via implicit widening.

    public long getId() { return id; }
    public void setId(int id) { this.id = id; }

    public String getName() { return name; }
    public void setName(String name) { this.name = name; }

    public double getPrice() { return price; }
    public void setPrice(double price) { this.price = price; }

    public int getTotalNumber() { return totalNumber; }
    public void setTotalNumber(int totalNumber) { this.totalNumber = totalNumber; }

    /**
     * Returns a human-readable string representation of the item.
     * Useful for debugging, logging, and seeing the full object state.
     */
    @Override
    public String toString() {
        return "Item{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", price=" + price +
                ", totalNumber=" + totalNumber +
                '}';
    }
}
