// Package declaration — model layer POJO representing the USERS database table
package com.items.model;

// Timestamp is used to store login/password timestamps and OTP expiry from the DB
import java.sql.Timestamp;

/**
 * Maps to the USERS table with all its columns and constraints (documented below).
 * This is the main user account entity — used for login, registration, profile display,
 * password management, and OTP (One-Time Password) email verification.
 *
 * Database table: USERS
 * ─────────────────────────────────────────────────────────────────────
 *  Column          Type              Constraints
 * ─────────────────────────────────────────────────────────────────────
 *  id              NUMBER(10) PK     Auto-generated by DB sequence
 *  full_name       VARCHAR2(100)     NOT NULL, CHECK (3-100 chars)
 *  username        VARCHAR2(30)      NOT NULL, UNIQUE, CHECK (3-30 chars, alphanumeric start)
 *  email           VARCHAR2(255)     NOT NULL, UNIQUE, CHECK (valid email format)
 *  password_hash   VARCHAR2(255)     NOT NULL, CHECK (>= 32 chars, SHA-256 base64 output)
 *  salt            VARCHAR2(255)     NOT NULL, CHECK (>= 16 chars, random base64)
 *  is_active       NUMBER(1)         DEFAULT 1 NOT NULL  (soft-delete flag)
 *  is_verified     NUMBER(1)         DEFAULT 0 NOT NULL  (OTP verification status)
 *  otp_code        VARCHAR2(6)       (nullable — only set during registration OTP flow)
 *  otp_expires_at  TIMESTAMP         (nullable — OTP expiry timestamp, valid for 5 minutes)
 *  created_at      TIMESTAMP         DEFAULT CURRENT_TIMESTAMP NOT NULL
 *  updated_at      TIMESTAMP         (nullable — updated on every profile change)
 * ─────────────────────────────────────────────────────────────────────
 *
 * NOTE: The OTP columns (is_verified, otp_code, otp_expires_at) were added via
 * ALTER TABLE after the initial creation. The application handles missing columns
 * gracefully by catching SQLException and treating the user as verified.
 *
 * SQL to add OTP support to an existing USERS table:
 *   ALTER TABLE USERS ADD (
 *       otp_code VARCHAR2(6),
 *       otp_expires_at TIMESTAMP,
 *       is_verified NUMBER(1) DEFAULT 0 NOT NULL
 *   );
 *   ALTER TABLE USERS ADD CONSTRAINT CHK_USERS_IS_VERIFIED CHECK (is_verified IN (0, 1));
 */
public class User {

    // Unique user identifier — auto-generated by the database
    private long id;
    // User's full display name (e.g., "John Doe") — 3 to 100 characters
    private String fullName;
    // Unique login username — 3 to 30 chars, must start with a letter
    private String username;
    // Unique email address — used for login AND OTP verification
    private String email;
    // SHA-256 hashed password (base64-encoded) — never stores the plain text
    private String passwordHash;
    // Random per-user salt (base64-encoded) — ensures unique hashes even for identical passwords
    private String salt;
    // Account creation timestamp — set by the DB on INSERT
    private Timestamp createdAt;
    // Last profile update timestamp — set by the DB on every UPDATE
    private Timestamp updatedAt;
    // Soft-delete flag: 1 = active, 0 = deleted/inactive
    private int isActive = 1;
    // OTP verification status: 1 = verified, 0 = pending verification
    private int isVerified = 0;
    // The 6-digit OTP code sent to the user's email during registration
    private String otpCode;
    // Timestamp when the OTP expires — OTP is only valid before this time
    private Timestamp otpExpiresAt;

    /** Default constructor — required for JSP useBean and reflection-based frameworks. */
    public User() {}

    /**
     * Minimal constructor for login lookup.
     * The user enters a username/email and a plain-text password;
     * the password will be hashed later for comparison.
     *
     * @param username     the login identifier (can be username OR email)
     * @param passwordHash the plain-text password (hashed later during verification)
     */
    public User(String username, String passwordHash) {
        this.username = username;
        this.passwordHash = passwordHash;
    }

    /**
     * Constructor for updating user profile information (name + email).
     *
     * @param id       the user's database ID
     * @param fullName the new display name
     * @param email    the new email address
     * @param passwordHash placeholder (null when not changing password)
     * @param salt     placeholder (null when not changing password)
     */
    public User(long id, String fullName, String email, String passwordHash, String salt) {
        this.id = id;
        this.fullName = fullName;
        this.email = email;
        this.passwordHash = passwordHash;
        this.salt = salt;
    }

    /**
     * Full constructor for new user registration (no ID — DB will assign it).
     *
     * @param fullName     the user's display name
     * @param username     the unique login username
     * @param email        the unique email address
     * @param passwordHash the SHA-256 hashed password
     * @param salt         the per-user random salt
     */
    public User(String fullName, String username, String email, String passwordHash, String salt) {
        this.fullName = fullName;
        this.username = username;
        this.email = email;
        this.passwordHash = passwordHash;
        this.salt = salt;
    }

    /**
     * Full constructor with all fields — used when reading a user from the DB
     * and displaying the full profile.
     *
     * @param id            database ID
     * @param fullName      display name
     * @param username      login username
     * @param email         email address
     * @param passwordHash  hashed password
     * @param salt          password salt
     * @param createdAt     account creation timestamp (as string)
     * @param updatedAt     last update timestamp (as string, can be null)
     */
    public User(long id, String fullName, String username, String email, String passwordHash, String salt, String createdAt, String updatedAt) {
        this.id = id;
        this.fullName = fullName;
        this.username = username;
        this.email = email;
        this.passwordHash = passwordHash;
        this.salt = salt;
        this.createdAt = Timestamp.valueOf(createdAt);
        this.updatedAt = updatedAt != null ? Timestamp.valueOf(updatedAt) : null;
    }

    /**
     * Constructor for listing users — excludes sensitive fields (password, salt).
     *
     * @param id        database ID
     * @param username  login username
     * @param fullName  display name
     * @param email     email address
     * @param createdAt account creation timestamp (as string)
     * @param updatedAt last update timestamp (as string, can be null)
     * @param isActive  account status (1 = active, 0 = inactive)
     */
    public User(long id, String username, String fullName, String email, String createdAt, String updatedAt, int isActive) {
        this.id = id;
        this.username = username;
        this.fullName = fullName;
        this.email = email;
        this.createdAt = Timestamp.valueOf(createdAt);
        this.updatedAt = updatedAt != null ? Timestamp.valueOf(updatedAt) : null;
        this.isActive = isActive;
    }

    // --- Getters and setters for every field ---
    // Standard Java Bean naming convention:
    //   - boolean/int fields use "get" prefix (e.g., getIsActive)
    //   - Object fields use "get" prefix (e.g., getFullName)
    //   - All fields have corresponding set methods

    public long getId() { return id; }
    public void setId(long id) { this.id = id; }

    public String getFullName() { return fullName; }
    public void setFullName(String fullName) { this.fullName = fullName; }

    public String getUsername() { return username; }
    public void setUsername(String username) { this.username = username; }

    public String getEmail() { return email; }
    public void setEmail(String email) { this.email = email; }

    public String getPasswordHash() { return passwordHash; }
    public void setPasswordHash(String passwordHash) { this.passwordHash = passwordHash; }

    public String getSalt() { return salt; }
    public void setSalt(String salt) { this.salt = salt; }

    public Timestamp getCreatedAt() { return createdAt; }
    public void setCreatedAt(Timestamp createdAt) { this.createdAt = createdAt; }

    public Timestamp getUpdatedAt() { return updatedAt; }
    public void setUpdatedAt(Timestamp updatedAt) { this.updatedAt = updatedAt; }

    public int getIsActive() { return isActive; }
    public void setIsActive(int isActive) { this.isActive = isActive; }

    public int getIsVerified() { return isVerified; }
    public void setIsVerified(int isVerified) { this.isVerified = isVerified; }

    public String getOtpCode() { return otpCode; }
    public void setOtpCode(String otpCode) { this.otpCode = otpCode; }

    public Timestamp getOtpExpiresAt() { return otpExpiresAt; }
    public void setOtpExpiresAt(Timestamp otpExpiresAt) { this.otpExpiresAt = otpExpiresAt; }

    /**
     * Returns a safe, readable string representation of the user.
     * Sensitive fields (passwordHash, salt, otpCode) are deliberately excluded.
     */
    @Override
    public String toString() {
        return "User{" +
                "id=" + id +
                ", fullName='" + fullName + '\'' +
                ", username='" + username + '\'' +
                ", email='" + email + '\'' +
                ", isActive=" + isActive +
                ", isVerified=" + isVerified +
                '}';
    }
}
