// Package declaration — this interface defines the service contract for Item CRUD operations
package com.items.service;

// List is used to return multiple items from the database
import java.util.List;
// Item is the domain model that this service manages
import com.items.model.Item;

/**
 * Service-layer interface that defines ALL business operations for the Item entity.
 *
 * The service layer sits between the Controller (which handles HTTP) and the
 * actual JDBC data access. This interface:
 *   1. Provides a clean API contract for the controller to call
 *   2. Allows the implementation to be swapped (JDBC, JPA, mock, etc.)
 *   3. Shields the controller from database-specific exceptions by wrapping
 *      SQLException in RuntimeException
 */
public interface ItemService {

    /**
     * Retrieves ALL items from the database.
     * Used on the dashboard page to display the full inventory.
     *
     * @return a List of every Item record in the ITEMS table (never null, may be empty)
     */
    List<Item> getItems();

    /**
     * Finds a single item by its primary key (ID).
     * Used when pre-filling the update form or when showing item details.
     *
     * @param id the item's database ID
     * @return the Item if found, or null if no record exists with that ID
     */
    Item getItemById(long id);

    /**
     * Inserts a NEW item into the database.
     * The ID is auto-generated by the DB and is ignored in the insert statement.
     *
     * @param item the Item object to insert (must not have an ID set)
     * @return true if the insert was successful
     * @throws RuntimeException wrapping SQLException on DB constraint violations
     *         (unique name, check constraint failure, etc.)
     */
    boolean addItem(Item item);

    /**
     * Updates an EXISTING item's fields (name, price, quantity).
     * The item is identified by its ID — all other fields are overwritten.
     *
     * @param item the Item with the updated values (ID must match an existing record)
     * @return true if at least one row was affected
     * @throws RuntimeException wrapping SQLException on DB constraint violations
     */
    boolean updateItem(Item item);

    /**
     * Deletes an item by its ID. Also deletes the associated item detail record
     * (the caller is responsible for deleting child records first).
     *
     * @param id the ID of the item to remove
     * @return true if a record was deleted
     * @throws RuntimeException wrapping SQLException if a foreign-key constraint
     *         prevents deletion (e.g., child records still exist)
     */
    boolean removeItemById(long id);
}
